name: Check package.xml 2

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'branch to run analysis'
        required: true
        default: 'none'

jobs:
  check-components:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: ${{ github.event.inputs}}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict

    - name: Run components python script
      run: nihaal2/Azure-Project-8-4/python_test.py
